#spring.application.name: carenet-api
#spring.profiles.active: local
#
#spring:
#  config:
#    import:
#      - storage.yml
#  web.resources.add-mappings: false
#
#server:
#  tomcat:
#    max-connections: 200000
#    threads:
#      max: 600
#      min-spare: 100
#
#---
#
#spring.config.activate.on-profile: local