name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.REPO_KEY}}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant excute permission for build
        run: chmod +x gradlew
        shell: bash
      - name: Build with Gradle
        run: ./gradlew clean build

      # 6. SSH key 설정 및 파일 전송
      - name: ssh key with passphrase
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/api-0.0.1-SNAPSHOT.jar"
          target: "/var/www/carenet/backend"
          strip_components: 3


